# coding: utf-8

"""
    FINBOURNE Insights API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import re  # noqa: F401
import io
import warnings

from pydantic.v1 import validate_arguments, ValidationError
from typing import overload, Optional, Union, Awaitable

from pydantic.v1 import Field, StrictStr
from typing import List, Optional
from typing_extensions import Annotated
from finbourne_insights.models.metrics_response import MetricsResponse

from finbourne_insights.api_client import ApiClient
from finbourne_insights.api_response import ApiResponse
from finbourne_insights.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)
from finbourne_insights.extensions.configuration_options import ConfigurationOptions

# ensure templated type usages are imported
from pydantic.v1 import Field, StrictStr
from typing import Optional
from typing_extensions import Annotated

class MetricsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @overload
    async def get_metrics(self, include : Annotated[Optional[List[StrictStr]], Field(description="The data sets to return, by name. Omit to return all of them. Repeat the parameter to request several, for example `?include=RequestsPerMinute&include=IdentityMetrics`. Matched case-insensitively against the data set names, which are the `name` values on the response's data sets; duplicates are ignored.")] = None, **kwargs) -> MetricsResponse:  # noqa: E501
        ...

    @overload
    def get_metrics(self, include : Annotated[Optional[List[StrictStr]], Field(description="The data sets to return, by name. Omit to return all of them. Repeat the parameter to request several, for example `?include=RequestsPerMinute&include=IdentityMetrics`. Matched case-insensitively against the data set names, which are the `name` values on the response's data sets; duplicates are ignored.")] = None, async_req: Optional[bool]=True, **kwargs) -> MetricsResponse:  # noqa: E501
        ...

    @validate_arguments
    def get_metrics(self, include : Annotated[Optional[List[StrictStr]], Field(description="The data sets to return, by name. Omit to return all of them. Repeat the parameter to request several, for example `?include=RequestsPerMinute&include=IdentityMetrics`. Matched case-insensitively against the data set names, which are the `name` values on the response's data sets; duplicates are ignored.")] = None, async_req: Optional[bool]=None, **kwargs) -> Union[MetricsResponse, Awaitable[MetricsResponse]]:  # noqa: E501
        """[EARLY ACCESS] GetMetrics: Get the aggregated platform metrics for the caller's domain.  # noqa: E501

         Returns request volumes, error rates and duration distributions for the domain's services, plus its identity             population and activity counts. The domain is taken from the authenticated request, never from a parameter.  <b>This endpoint is slow by design.</b> It runs several analytical queries in parallel and commonly takes             upwards of thirty seconds when the underlying data is cold. The server abandons a data set that has not             completed within its configured budget and reports it in `failed`, so a call returns rather than hanging             indefinitely; allow comfortably more than that budget on the client, and do not call this on a             user-interactive code path without showing progress.  Partial success is normal and is still reported as a `200`. A data set that could not be retrieved is             null in the response and named in `failed` with a reason; a data set excluded via             include is null and named in `notIncluded`. Render a null data set as unavailable             rather than as an absence of activity.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_metrics(include, async_req=True)
        >>> result = thread.get()

        :param include: The data sets to return, by name. Omit to return all of them. Repeat the parameter to request several, for example `?include=RequestsPerMinute&include=IdentityMetrics`. Matched case-insensitively against the data set names, which are the `name` values on the response's data sets; duplicates are ignored.
        :type include: List[str]
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: MetricsResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_metrics_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.get_metrics_with_http_info(include, **kwargs)  # noqa: E501

    @validate_arguments
    def get_metrics_with_http_info(self, include : Annotated[Optional[List[StrictStr]], Field(description="The data sets to return, by name. Omit to return all of them. Repeat the parameter to request several, for example `?include=RequestsPerMinute&include=IdentityMetrics`. Matched case-insensitively against the data set names, which are the `name` values on the response's data sets; duplicates are ignored.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """[EARLY ACCESS] GetMetrics: Get the aggregated platform metrics for the caller's domain.  # noqa: E501

         Returns request volumes, error rates and duration distributions for the domain's services, plus its identity             population and activity counts. The domain is taken from the authenticated request, never from a parameter.  <b>This endpoint is slow by design.</b> It runs several analytical queries in parallel and commonly takes             upwards of thirty seconds when the underlying data is cold. The server abandons a data set that has not             completed within its configured budget and reports it in `failed`, so a call returns rather than hanging             indefinitely; allow comfortably more than that budget on the client, and do not call this on a             user-interactive code path without showing progress.  Partial success is normal and is still reported as a `200`. A data set that could not be retrieved is             null in the response and named in `failed` with a reason; a data set excluded via             include is null and named in `notIncluded`. Render a null data set as unavailable             rather than as an absence of activity.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_metrics_with_http_info(include, async_req=True)
        >>> result = thread.get()

        :param include: The data sets to return, by name. Omit to return all of them. Repeat the parameter to request several, for example `?include=RequestsPerMinute&include=IdentityMetrics`. Matched case-insensitively against the data set names, which are the `name` values on the response's data sets; duplicates are ignored.
        :type include: List[str]
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(MetricsResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'include'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_metrics" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('include') is not None:  # noqa: E501
            _query_params.append(('include', _params['include']))
            _collection_formats['include'] = 'multi'

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "MetricsResponse",
            '400': "LusidValidationProblemDetails",
        }

        return self.api_client.call_api(
            '/api/metrics', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
