# coding: utf-8

"""
    FINBOURNE Insights API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class IdentityMetricsDataSet(BaseModel):
    """
    Identity population and activity counts for the domain, pivoted from the latest tranche the identity metrics provider collected.  # noqa: E501
    """
    name:  StrictStr = Field(...,alias="name", description="The name of this data set. Always `IdentityMetrics`, matching the corresponding Finbourne.Insights.WebApi.Dtos.Metrics.MetricDataSet value and Finbourne.Insights.WebApi.Dtos.Metrics.MetricsResponse property.") 
    collected_at: Optional[datetime] = Field(default=None, description="The timestamp of the tranche these values were collected in, in UTC, or null if no tranche was returned.", alias="collectedAt")
    personal_users: Optional[StrictInt] = Field(default=None, description="The number of personal (human) users in the domain, or null if not reported.", alias="personalUsers")
    service_users: Optional[StrictInt] = Field(default=None, description="The number of service users in the domain, or null if not reported.", alias="serviceUsers")
    never_logged_in: Optional[StrictInt] = Field(default=None, description="The number of users that have never logged in, or null if not reported.", alias="neverLoggedIn")
    ignored: Optional[StrictInt] = Field(default=None, description="The number of users excluded from the other counts, or null if not reported.")
    account_locked: Optional[StrictInt] = Field(default=None, description="The number of users whose account is locked, or null if not reported.", alias="accountLocked")
    suspended_pw_reset: Optional[StrictInt] = Field(default=None, description="The number of users suspended pending a password reset, or null if not reported.", alias="suspendedPwReset")
    created_last24_hours: Optional[StrictInt] = Field(default=None, description="The number of users created in the last 24 hours, or null if not reported.", alias="createdLast24Hours")
    created_last7_days: Optional[StrictInt] = Field(default=None, description="The number of users created in the last 7 days, or null if not reported.", alias="createdLast7Days")
    created_last30_days: Optional[StrictInt] = Field(default=None, description="The number of users created in the last 30 days, or null if not reported.", alias="createdLast30Days")
    active_last24_hours: Optional[StrictInt] = Field(default=None, description="The number of users active in the last 24 hours, or null if not reported.", alias="activeLast24Hours")
    active_last7_days: Optional[StrictInt] = Field(default=None, description="The number of users active in the last 7 days, or null if not reported.", alias="activeLast7Days")
    active_last30_days: Optional[StrictInt] = Field(default=None, description="The number of users active in the last 30 days, or null if not reported.", alias="activeLast30Days")
    __properties = ["name", "collectedAt", "personalUsers", "serviceUsers", "neverLoggedIn", "ignored", "accountLocked", "suspendedPwReset", "createdLast24Hours", "createdLast7Days", "createdLast30Days", "activeLast24Hours", "activeLast7Days", "activeLast30Days"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> IdentityMetricsDataSet:
        """Create an instance of IdentityMetricsDataSet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if collected_at (nullable) is None
        # and __fields_set__ contains the field
        if self.collected_at is None and "collected_at" in self.__fields_set__:
            _dict['collectedAt'] = None

        # set to None if personal_users (nullable) is None
        # and __fields_set__ contains the field
        if self.personal_users is None and "personal_users" in self.__fields_set__:
            _dict['personalUsers'] = None

        # set to None if service_users (nullable) is None
        # and __fields_set__ contains the field
        if self.service_users is None and "service_users" in self.__fields_set__:
            _dict['serviceUsers'] = None

        # set to None if never_logged_in (nullable) is None
        # and __fields_set__ contains the field
        if self.never_logged_in is None and "never_logged_in" in self.__fields_set__:
            _dict['neverLoggedIn'] = None

        # set to None if ignored (nullable) is None
        # and __fields_set__ contains the field
        if self.ignored is None and "ignored" in self.__fields_set__:
            _dict['ignored'] = None

        # set to None if account_locked (nullable) is None
        # and __fields_set__ contains the field
        if self.account_locked is None and "account_locked" in self.__fields_set__:
            _dict['accountLocked'] = None

        # set to None if suspended_pw_reset (nullable) is None
        # and __fields_set__ contains the field
        if self.suspended_pw_reset is None and "suspended_pw_reset" in self.__fields_set__:
            _dict['suspendedPwReset'] = None

        # set to None if created_last24_hours (nullable) is None
        # and __fields_set__ contains the field
        if self.created_last24_hours is None and "created_last24_hours" in self.__fields_set__:
            _dict['createdLast24Hours'] = None

        # set to None if created_last7_days (nullable) is None
        # and __fields_set__ contains the field
        if self.created_last7_days is None and "created_last7_days" in self.__fields_set__:
            _dict['createdLast7Days'] = None

        # set to None if created_last30_days (nullable) is None
        # and __fields_set__ contains the field
        if self.created_last30_days is None and "created_last30_days" in self.__fields_set__:
            _dict['createdLast30Days'] = None

        # set to None if active_last24_hours (nullable) is None
        # and __fields_set__ contains the field
        if self.active_last24_hours is None and "active_last24_hours" in self.__fields_set__:
            _dict['activeLast24Hours'] = None

        # set to None if active_last7_days (nullable) is None
        # and __fields_set__ contains the field
        if self.active_last7_days is None and "active_last7_days" in self.__fields_set__:
            _dict['activeLast7Days'] = None

        # set to None if active_last30_days (nullable) is None
        # and __fields_set__ contains the field
        if self.active_last30_days is None and "active_last30_days" in self.__fields_set__:
            _dict['activeLast30Days'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> IdentityMetricsDataSet:
        """Create an instance of IdentityMetricsDataSet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return IdentityMetricsDataSet.parse_obj(obj)

        _obj = IdentityMetricsDataSet.parse_obj({
            "name": obj.get("name"),
            "collected_at": obj.get("collectedAt"),
            "personal_users": obj.get("personalUsers"),
            "service_users": obj.get("serviceUsers"),
            "never_logged_in": obj.get("neverLoggedIn"),
            "ignored": obj.get("ignored"),
            "account_locked": obj.get("accountLocked"),
            "suspended_pw_reset": obj.get("suspendedPwReset"),
            "created_last24_hours": obj.get("createdLast24Hours"),
            "created_last7_days": obj.get("createdLast7Days"),
            "created_last30_days": obj.get("createdLast30Days"),
            "active_last24_hours": obj.get("activeLast24Hours"),
            "active_last7_days": obj.get("activeLast7Days"),
            "active_last30_days": obj.get("activeLast30Days")
        })
        return _obj

IdentityMetricsDataSet.update_forward_refs()
