# coding: utf-8

"""
    FINBOURNE Insights API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from finbourne_insights.models.boolean_comparator import BooleanComparator
from finbourne_insights.models.date_comparator import DateComparator
from finbourne_insights.models.numeric_comparator import NumericComparator
from finbourne_insights.models.text_comparator import TextComparator

class InsightsFilter(BaseModel):
    """
    A single filter applied to a queryable log field. Exactly one comparator (Finbourne.Insights.WebApi.Dtos.Querying.InsightsFilter.Text, Finbourne.Insights.WebApi.Dtos.Querying.InsightsFilter.Numeric, Finbourne.Insights.WebApi.Dtos.Querying.InsightsFilter.Date or Finbourne.Insights.WebApi.Dtos.Querying.InsightsFilter.Boolean) must be populated, and its type must match the data type of the field named by Finbourne.Insights.WebApi.Dtos.Querying.InsightsFilter.Field. The available comparator and operation for a field can be discovered via the queryable-fields metadata endpoint.  # noqa: E501
    """
    field:  StrictStr = Field(...,alias="field", description="The name of the field to filter on (case-insensitive). Must be a filterable field of the queried log type.") 
    text: Optional[TextComparator] = None
    numeric: Optional[NumericComparator] = None
    var_date: Optional[DateComparator] = Field(default=None, alias="date")
    boolean: Optional[BooleanComparator] = None
    __properties = ["field", "text", "numeric", "date", "boolean"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> InsightsFilter:
        """Create an instance of InsightsFilter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of text
        if self.text:
            _dict['text'] = self.text.to_dict()
        # override the default output from pydantic by calling `to_dict()` of numeric
        if self.numeric:
            _dict['numeric'] = self.numeric.to_dict()
        # override the default output from pydantic by calling `to_dict()` of var_date
        if self.var_date:
            _dict['date'] = self.var_date.to_dict()
        # override the default output from pydantic by calling `to_dict()` of boolean
        if self.boolean:
            _dict['boolean'] = self.boolean.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> InsightsFilter:
        """Create an instance of InsightsFilter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return InsightsFilter.parse_obj(obj)

        _obj = InsightsFilter.parse_obj({
            "field": obj.get("field"),
            "text": TextComparator.from_dict(obj.get("text")) if obj.get("text") is not None else None,
            "numeric": NumericComparator.from_dict(obj.get("numeric")) if obj.get("numeric") is not None else None,
            "var_date": DateComparator.from_dict(obj.get("date")) if obj.get("date") is not None else None,
            "boolean": BooleanComparator.from_dict(obj.get("boolean")) if obj.get("boolean") is not None else None
        })
        return _obj

InsightsFilter.update_forward_refs()
