# coding: utf-8

"""
    FINBOURNE Insights API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from finbourne_insights.models.identity_metrics_data_set import IdentityMetricsDataSet
from finbourne_insights.models.link import Link
from finbourne_insights.models.metric_data_set_failure import MetricDataSetFailure
from finbourne_insights.models.requests_per_minute_data_set import RequestsPerMinuteDataSet
from finbourne_insights.models.service_endpoint_durations24h_data_set import ServiceEndpointDurations24hDataSet
from finbourne_insights.models.service_requests24h_data_set import ServiceRequests24hDataSet

class MetricsResponse(BaseModel):
    """
    The aggregated platform metrics for a domain: one nullable, strongly-typed property per data set.  # noqa: E501
    """
    as_at: datetime = Field(description="When this response was assembled, in UTC. Every data set in the response was resolved against this instant.", alias="asAt")
    domain:  StrictStr = Field(...,alias="domain", description="The domain the metrics are for, resolved from the authenticated request rather than from any parameter.") 
    requests_per_minute: Optional[RequestsPerMinuteDataSet] = Field(default=None, alias="requestsPerMinute")
    service_endpoint_durations24h: Optional[ServiceEndpointDurations24hDataSet] = Field(default=None, alias="serviceEndpointDurations24h")
    service_requests24h: Optional[ServiceRequests24hDataSet] = Field(default=None, alias="serviceRequests24h")
    identity_metrics: Optional[IdentityMetricsDataSet] = Field(default=None, alias="identityMetrics")
    not_included: List[StrictStr] = Field(description="The data sets the caller excluded via the `include` parameter, and which were therefore never queried. Each value is one of the Finbourne.Insights.WebApi.Dtos.Metrics.MetricDataSet values.", alias="notIncluded")
    failed: List[MetricDataSetFailure] = Field(description="The data sets that were requested but could not be returned, each with a caller-safe reason.")
    links: Optional[List[Link]] = None
    __properties = ["asAt", "domain", "requestsPerMinute", "serviceEndpointDurations24h", "serviceRequests24h", "identityMetrics", "notIncluded", "failed", "links"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MetricsResponse:
        """Create an instance of MetricsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of requests_per_minute
        if self.requests_per_minute:
            _dict['requestsPerMinute'] = self.requests_per_minute.to_dict()
        # override the default output from pydantic by calling `to_dict()` of service_endpoint_durations24h
        if self.service_endpoint_durations24h:
            _dict['serviceEndpointDurations24h'] = self.service_endpoint_durations24h.to_dict()
        # override the default output from pydantic by calling `to_dict()` of service_requests24h
        if self.service_requests24h:
            _dict['serviceRequests24h'] = self.service_requests24h.to_dict()
        # override the default output from pydantic by calling `to_dict()` of identity_metrics
        if self.identity_metrics:
            _dict['identityMetrics'] = self.identity_metrics.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in failed (list)
        _items = []
        if self.failed:
            for _item in self.failed:
                if _item:
                    _items.append(_item.to_dict())
            _dict['failed'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in links (list)
        _items = []
        if self.links:
            for _item in self.links:
                if _item:
                    _items.append(_item.to_dict())
            _dict['links'] = _items
        # set to None if links (nullable) is None
        # and __fields_set__ contains the field
        if self.links is None and "links" in self.__fields_set__:
            _dict['links'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MetricsResponse:
        """Create an instance of MetricsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return MetricsResponse.parse_obj(obj)

        _obj = MetricsResponse.parse_obj({
            "as_at": obj.get("asAt"),
            "domain": obj.get("domain"),
            "requests_per_minute": RequestsPerMinuteDataSet.from_dict(obj.get("requestsPerMinute")) if obj.get("requestsPerMinute") is not None else None,
            "service_endpoint_durations24h": ServiceEndpointDurations24hDataSet.from_dict(obj.get("serviceEndpointDurations24h")) if obj.get("serviceEndpointDurations24h") is not None else None,
            "service_requests24h": ServiceRequests24hDataSet.from_dict(obj.get("serviceRequests24h")) if obj.get("serviceRequests24h") is not None else None,
            "identity_metrics": IdentityMetricsDataSet.from_dict(obj.get("identityMetrics")) if obj.get("identityMetrics") is not None else None,
            "not_included": obj.get("notIncluded"),
            "failed": [MetricDataSetFailure.from_dict(_item) for _item in obj.get("failed")] if obj.get("failed") is not None else None,
            "links": [Link.from_dict(_item) for _item in obj.get("links")] if obj.get("links") is not None else None
        })
        return _obj

MetricsResponse.update_forward_refs()
