# coding: utf-8

"""
    FINBOURNE Insights API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class QueryableLogField(BaseModel):
    """
    Describes a field of a log type that can be selected and (where Finbourne.Insights.WebApi.Dtos.Querying.QueryableLogField.Filterable is set) filtered when querying logs, including the comparator operations available for it. Returned by the queryable-fields metadata endpoint so a UI can advertise the correct comparators for each field.  # noqa: E501
    """
    name:  StrictStr = Field(...,alias="name", description="The name of the field, as used when requesting it or filtering on it (case-insensitive).") 
    data_type:  StrictStr = Field(...,alias="dataType", description="The data type of the field: Text, Numeric, Date or Boolean.") 
    supported_operations: List[StrictStr] = Field(description="The comparator operations available for this field. Empty when the field is not filterable.", alias="supportedOperations")
    filterable: Optional[StrictBool] = Field(default=None, description="Whether the field can be used in a filter.")
    always_returned: Optional[StrictBool] = Field(default=None, description="Whether the field is always returned (and therefore need not be requested).", alias="alwaysReturned")
    __properties = ["name", "dataType", "supportedOperations", "filterable", "alwaysReturned"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> QueryableLogField:
        """Create an instance of QueryableLogField from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> QueryableLogField:
        """Create an instance of QueryableLogField from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return QueryableLogField.parse_obj(obj)

        _obj = QueryableLogField.parse_obj({
            "name": obj.get("name"),
            "data_type": obj.get("dataType"),
            "supported_operations": obj.get("supportedOperations"),
            "filterable": obj.get("filterable"),
            "always_returned": obj.get("alwaysReturned")
        })
        return _obj

QueryableLogField.update_forward_refs()
