# coding: utf-8

"""
    FINBOURNE Insights API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from finbourne_insights.models.insights_filter import InsightsFilter
from finbourne_insights.models.time_range import TimeRange

class QueryRequestLogsRequest(BaseModel):
    """
    Body of the QueryRequestLogs endpoint. A query is bounded by a time range (Finbourne.Insights.WebApi.Dtos.QueryRequestLogsRequest.StartAt/Finbourne.Insights.WebApi.Dtos.QueryRequestLogsRequest.EndAt) and refined by an optional set of Finbourne.Insights.WebApi.Dtos.QueryRequestLogsRequest.Filters that are combined with logical AND. The discoverable set of filterable fields, their data types and the operations available for each is returned by the queryable-fields metadata endpoint.  # noqa: E501
    """
    start_at: Optional[datetime] = Field(default=None, description="The inclusive start of the time range to query. Required unless Finbourne.Insights.WebApi.Dtos.QueryRequestLogsRequest.Page is supplied. Used to bound the underlying partition scan, so a tighter range is cheaper and faster.", alias="startAt")
    end_at: Optional[datetime] = Field(default=None, description="The end of the time range to query. Required unless Finbourne.Insights.WebApi.Dtos.QueryRequestLogsRequest.Page or Finbourne.Insights.WebApi.Dtos.QueryRequestLogsRequest.TimeRange is supplied.", alias="endAt")
    time_range: Optional[TimeRange] = Field(default=None, alias="timeRange")
    filters: Optional[List[InsightsFilter]] = Field(default=None, description="Optional filters to apply, combined with logical AND. Each filter targets a filterable field and supplies exactly one comparator matching that field's data type.")
    sort_by:  Optional[StrictStr] = Field(None,alias="sortBy", description="Order the results by these fields. Use the '-' sign to denote descending order e.g. -MyFieldName. Multiple fields can be denoted by a comma e.g. -MyFieldName,AnotherFieldName,-AFurtherFieldName.") 
    max_results: Optional[StrictInt] = Field(default=None, description="The maximum total number of records to capture in the result set; applied as the Luminesce query limit and so bounding the work the query performs. The minimum value is 1 and the maximum is 10000; defaults to 500 when not supplied. The per-page limit then controls how many of these captured records are returned per page.", alias="maxResults")
    limit: Optional[StrictInt] = Field(default=None, description="When paginating, only return this number of records per page. The minimum value is 0 (return all captured records in a single page) and the maximum is 10000.")
    page:  Optional[StrictStr] = Field(None,alias="page", description="Encoded page string returned from a previous search result that will retrieve the next page of data. When this field is supplied, the query-defining fields should not be supplied.") 
    fields: Optional[List[StrictStr]] = Field(default=None, description="Optional list of additional field names to include in the response. The fields Timestamp, Id, Application and Operation are always returned. Values are matched case-insensitively against the queryable fields of the request logs.")
    __properties = ["startAt", "endAt", "timeRange", "filters", "sortBy", "maxResults", "limit", "page", "fields"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> QueryRequestLogsRequest:
        """Create an instance of QueryRequestLogsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of time_range
        if self.time_range:
            _dict['timeRange'] = self.time_range.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in filters (list)
        _items = []
        if self.filters:
            for _item in self.filters:
                if _item:
                    _items.append(_item.to_dict())
            _dict['filters'] = _items
        # set to None if start_at (nullable) is None
        # and __fields_set__ contains the field
        if self.start_at is None and "start_at" in self.__fields_set__:
            _dict['startAt'] = None

        # set to None if end_at (nullable) is None
        # and __fields_set__ contains the field
        if self.end_at is None and "end_at" in self.__fields_set__:
            _dict['endAt'] = None

        # set to None if filters (nullable) is None
        # and __fields_set__ contains the field
        if self.filters is None and "filters" in self.__fields_set__:
            _dict['filters'] = None

        # set to None if sort_by (nullable) is None
        # and __fields_set__ contains the field
        if self.sort_by is None and "sort_by" in self.__fields_set__:
            _dict['sortBy'] = None

        # set to None if max_results (nullable) is None
        # and __fields_set__ contains the field
        if self.max_results is None and "max_results" in self.__fields_set__:
            _dict['maxResults'] = None

        # set to None if page (nullable) is None
        # and __fields_set__ contains the field
        if self.page is None and "page" in self.__fields_set__:
            _dict['page'] = None

        # set to None if fields (nullable) is None
        # and __fields_set__ contains the field
        if self.fields is None and "fields" in self.__fields_set__:
            _dict['fields'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> QueryRequestLogsRequest:
        """Create an instance of QueryRequestLogsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return QueryRequestLogsRequest.parse_obj(obj)

        _obj = QueryRequestLogsRequest.parse_obj({
            "start_at": obj.get("startAt"),
            "end_at": obj.get("endAt"),
            "time_range": TimeRange.from_dict(obj.get("timeRange")) if obj.get("timeRange") is not None else None,
            "filters": [InsightsFilter.from_dict(_item) for _item in obj.get("filters")] if obj.get("filters") is not None else None,
            "sort_by": obj.get("sortBy"),
            "max_results": obj.get("maxResults"),
            "limit": obj.get("limit"),
            "page": obj.get("page"),
            "fields": obj.get("fields")
        })
        return _obj

QueryRequestLogsRequest.update_forward_refs()
