# coding: utf-8

"""
    FINBOURNE Insights API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from finbourne_insights.models.relative_offset import RelativeOffset

class RelativeBoundary(BaseModel):
    """
    One end of a relative time range. Exactly one of the options must be set: Finbourne.Insights.WebApi.Dtos.Querying.RelativeBoundary.Now (the current instant), Finbourne.Insights.WebApi.Dtos.Querying.RelativeBoundary.Midnight (the start of the current day in the range's time zone), Finbourne.Insights.WebApi.Dtos.Querying.RelativeBoundary.Offset (a duration back from now) or Finbourne.Insights.WebApi.Dtos.Querying.RelativeBoundary.Absolute (an explicit instant).  # noqa: E501
    """
    now: Optional[StrictBool] = Field(default=None, description="When `true`, this boundary is the current instant (\"now\").")
    midnight: Optional[StrictBool] = Field(default=None, description="When `true`, this boundary is the start of the current day (midnight) in the range's time zone.")
    offset: Optional[RelativeOffset] = None
    absolute: Optional[datetime] = Field(default=None, description="An explicit absolute instant.")
    __properties = ["now", "midnight", "offset", "absolute"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RelativeBoundary:
        """Create an instance of RelativeBoundary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of offset
        if self.offset:
            _dict['offset'] = self.offset.to_dict()
        # set to None if absolute (nullable) is None
        # and __fields_set__ contains the field
        if self.absolute is None and "absolute" in self.__fields_set__:
            _dict['absolute'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RelativeBoundary:
        """Create an instance of RelativeBoundary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RelativeBoundary.parse_obj(obj)

        _obj = RelativeBoundary.parse_obj({
            "now": obj.get("now"),
            "midnight": obj.get("midnight"),
            "offset": RelativeOffset.from_dict(obj.get("offset")) if obj.get("offset") is not None else None,
            "absolute": obj.get("absolute")
        })
        return _obj

RelativeBoundary.update_forward_refs()
