# coding: utf-8

"""
    FINBOURNE Insights API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class RequestsPerMinuteBucket(BaseModel):
    """
    One minute of request activity for a single service and endpoint.  # noqa: E501
    """
    minute_bucket: datetime = Field(description="Start of the whole minute this row covers, in UTC.", alias="minuteBucket")
    service:  Optional[StrictStr] = Field(None,alias="service", description="The name of the service (application) that handled the requests.") 
    endpoint:  Optional[StrictStr] = Field(None,alias="endpoint", description="The endpoint (API operation) the requests were made to.") 
    total_requests: Optional[StrictInt] = Field(default=None, description="The number of requests in this minute, or null if not reported.", alias="totalRequests")
    requests5xx: Optional[StrictInt] = Field(default=None, description="The number of requests in this minute that returned a 5xx status code, or null if not reported.")
    duration_sum_ms: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The sum of the request durations in this minute, in milliseconds, or null if not reported.", alias="durationSumMs")
    __properties = ["minuteBucket", "service", "endpoint", "totalRequests", "requests5xx", "durationSumMs"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RequestsPerMinuteBucket:
        """Create an instance of RequestsPerMinuteBucket from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if service (nullable) is None
        # and __fields_set__ contains the field
        if self.service is None and "service" in self.__fields_set__:
            _dict['service'] = None

        # set to None if endpoint (nullable) is None
        # and __fields_set__ contains the field
        if self.endpoint is None and "endpoint" in self.__fields_set__:
            _dict['endpoint'] = None

        # set to None if total_requests (nullable) is None
        # and __fields_set__ contains the field
        if self.total_requests is None and "total_requests" in self.__fields_set__:
            _dict['totalRequests'] = None

        # set to None if requests5xx (nullable) is None
        # and __fields_set__ contains the field
        if self.requests5xx is None and "requests5xx" in self.__fields_set__:
            _dict['requests5xx'] = None

        # set to None if duration_sum_ms (nullable) is None
        # and __fields_set__ contains the field
        if self.duration_sum_ms is None and "duration_sum_ms" in self.__fields_set__:
            _dict['durationSumMs'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RequestsPerMinuteBucket:
        """Create an instance of RequestsPerMinuteBucket from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RequestsPerMinuteBucket.parse_obj(obj)

        _obj = RequestsPerMinuteBucket.parse_obj({
            "minute_bucket": obj.get("minuteBucket"),
            "service": obj.get("service"),
            "endpoint": obj.get("endpoint"),
            "total_requests": obj.get("totalRequests"),
            "requests5xx": obj.get("requests5xx"),
            "duration_sum_ms": obj.get("durationSumMs")
        })
        return _obj

RequestsPerMinuteBucket.update_forward_refs()
