# coding: utf-8

"""
    FINBOURNE Insights API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class ServiceRequests(BaseModel):
    """
    The request volume and server-error rate for a single service over the window.  # noqa: E501
    """
    service:  Optional[StrictStr] = Field(None,alias="service", description="The name of the service (application) that handled the requests.") 
    total_requests: Optional[StrictInt] = Field(default=None, description="The number of requests over the window, or null if not reported.", alias="totalRequests")
    requests5xx: Optional[StrictInt] = Field(default=None, description="The number of requests over the window that returned a 5xx status code, or null if not reported.")
    pct5xx: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The percentage of requests that returned a 5xx status code, or null if not reported.")
    __properties = ["service", "totalRequests", "requests5xx", "pct5xx"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ServiceRequests:
        """Create an instance of ServiceRequests from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if service (nullable) is None
        # and __fields_set__ contains the field
        if self.service is None and "service" in self.__fields_set__:
            _dict['service'] = None

        # set to None if total_requests (nullable) is None
        # and __fields_set__ contains the field
        if self.total_requests is None and "total_requests" in self.__fields_set__:
            _dict['totalRequests'] = None

        # set to None if requests5xx (nullable) is None
        # and __fields_set__ contains the field
        if self.requests5xx is None and "requests5xx" in self.__fields_set__:
            _dict['requests5xx'] = None

        # set to None if pct5xx (nullable) is None
        # and __fields_set__ contains the field
        if self.pct5xx is None and "pct5xx" in self.__fields_set__:
            _dict['pct5xx'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ServiceRequests:
        """Create an instance of ServiceRequests from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ServiceRequests.parse_obj(obj)

        _obj = ServiceRequests.parse_obj({
            "service": obj.get("service"),
            "total_requests": obj.get("totalRequests"),
            "requests5xx": obj.get("requests5xx"),
            "pct5xx": obj.get("pct5xx")
        })
        return _obj

ServiceRequests.update_forward_refs()
