# coding: utf-8

"""
    FINBOURNE Insights API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from finbourne_insights.models.service_endpoint_duration import ServiceEndpointDuration

class ServiceEndpointDurations24hDataSet(BaseModel):
    """
    Request duration distribution per service and endpoint over a rolling twenty four hour window.  # noqa: E501
    """
    name:  StrictStr = Field(...,alias="name", description="The name of this data set. Always `ServiceEndpointDurations24h`, matching the corresponding Finbourne.Insights.WebApi.Dtos.Metrics.MetricDataSet value and Finbourne.Insights.WebApi.Dtos.Metrics.MetricsResponse property.") 
    window_start: datetime = Field(description="Inclusive start of the window the data covers, in UTC, floored to a whole minute.", alias="windowStart")
    window_end: datetime = Field(description="End of the window the data covers, in UTC, floored to a whole minute.", alias="windowEnd")
    truncated: StrictBool = Field(description="True when the query reached the row cap, so some services or endpoints are missing. False when the whole result set was returned.")
    values: List[ServiceEndpointDuration] = Field(description="The rows, ordered by service then endpoint.")
    __properties = ["name", "windowStart", "windowEnd", "truncated", "values"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ServiceEndpointDurations24hDataSet:
        """Create an instance of ServiceEndpointDurations24hDataSet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in values (list)
        _items = []
        if self.values:
            for _item in self.values:
                if _item:
                    _items.append(_item.to_dict())
            _dict['values'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ServiceEndpointDurations24hDataSet:
        """Create an instance of ServiceEndpointDurations24hDataSet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ServiceEndpointDurations24hDataSet.parse_obj(obj)

        _obj = ServiceEndpointDurations24hDataSet.parse_obj({
            "name": obj.get("name"),
            "window_start": obj.get("windowStart"),
            "window_end": obj.get("windowEnd"),
            "truncated": obj.get("truncated"),
            "values": [ServiceEndpointDuration.from_dict(_item) for _item in obj.get("values")] if obj.get("values") is not None else None
        })
        return _obj

ServiceEndpointDurations24hDataSet.update_forward_refs()
