# coding: utf-8

"""
    FINBOURNE Insights API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class ServiceEndpointDuration(BaseModel):
    """
    The request duration distribution for a single service and endpoint over the window.  # noqa: E501
    """
    service:  Optional[StrictStr] = Field(None,alias="service", description="The name of the service (application) that handled the requests.") 
    endpoint:  Optional[StrictStr] = Field(None,alias="endpoint", description="The endpoint (API operation) the requests were made to.") 
    total_requests: Optional[StrictInt] = Field(default=None, description="The number of requests over the window, or null if not reported.", alias="totalRequests")
    mean_duration_ms: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The mean request duration in milliseconds, or null if not reported.", alias="meanDurationMs")
    median_duration_ms: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The median (50th percentile) request duration in milliseconds, or null if not reported.", alias="medianDurationMs")
    p95_duration_ms: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The 95th percentile request duration in milliseconds, or null if not reported.", alias="p95DurationMs")
    __properties = ["service", "endpoint", "totalRequests", "meanDurationMs", "medianDurationMs", "p95DurationMs"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ServiceEndpointDuration:
        """Create an instance of ServiceEndpointDuration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if service (nullable) is None
        # and __fields_set__ contains the field
        if self.service is None and "service" in self.__fields_set__:
            _dict['service'] = None

        # set to None if endpoint (nullable) is None
        # and __fields_set__ contains the field
        if self.endpoint is None and "endpoint" in self.__fields_set__:
            _dict['endpoint'] = None

        # set to None if total_requests (nullable) is None
        # and __fields_set__ contains the field
        if self.total_requests is None and "total_requests" in self.__fields_set__:
            _dict['totalRequests'] = None

        # set to None if mean_duration_ms (nullable) is None
        # and __fields_set__ contains the field
        if self.mean_duration_ms is None and "mean_duration_ms" in self.__fields_set__:
            _dict['meanDurationMs'] = None

        # set to None if median_duration_ms (nullable) is None
        # and __fields_set__ contains the field
        if self.median_duration_ms is None and "median_duration_ms" in self.__fields_set__:
            _dict['medianDurationMs'] = None

        # set to None if p95_duration_ms (nullable) is None
        # and __fields_set__ contains the field
        if self.p95_duration_ms is None and "p95_duration_ms" in self.__fields_set__:
            _dict['p95DurationMs'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ServiceEndpointDuration:
        """Create an instance of ServiceEndpointDuration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ServiceEndpointDuration.parse_obj(obj)

        _obj = ServiceEndpointDuration.parse_obj({
            "service": obj.get("service"),
            "endpoint": obj.get("endpoint"),
            "total_requests": obj.get("totalRequests"),
            "mean_duration_ms": obj.get("meanDurationMs"),
            "median_duration_ms": obj.get("medianDurationMs"),
            "p95_duration_ms": obj.get("p95DurationMs")
        })
        return _obj

ServiceEndpointDuration.update_forward_refs()
