# coding: utf-8

"""
    FINBOURNE Insights API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from finbourne_insights.models.relative_boundary import RelativeBoundary

class TimeRange(BaseModel):
    """
    A server-resolved time window for a query, as an alternative to supplying absolute StartAt/EndAt. Supply either a Finbourne.Insights.WebApi.Dtos.Querying.TimeRange.Preset (e.g. LastWeek, CurrentMonth) or a relative range via Finbourne.Insights.WebApi.Dtos.Querying.TimeRange.From and Finbourne.Insights.WebApi.Dtos.Querying.TimeRange.To. The window is resolved on the server at query time, so a saved query re-runs against a sliding window. Calendar boundaries are anchored in Finbourne.Insights.WebApi.Dtos.Querying.TimeRange.TimeZone (default UTC); weeks start on Monday.  # noqa: E501
    """
    preset:  Optional[StrictStr] = Field(None,alias="preset", description="A named preset window. One of the Finbourne.Insights.WebApi.Dtos.Querying.TimeRangePreset values. Mutually exclusive with Finbourne.Insights.WebApi.Dtos.Querying.TimeRange.From/Finbourne.Insights.WebApi.Dtos.Querying.TimeRange.To.") 
    var_from: Optional[RelativeBoundary] = Field(default=None, alias="from")
    to: Optional[RelativeBoundary] = None
    time_zone:  Optional[StrictStr] = Field(None,alias="timeZone", description="Optional IANA time-zone identifier (e.g. \"Europe/London\") used to anchor calendar boundaries (start of day/week/month/quarter/year). Defaults to UTC when not supplied.") 
    __properties = ["preset", "from", "to", "timeZone"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TimeRange:
        """Create an instance of TimeRange from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of var_from
        if self.var_from:
            _dict['from'] = self.var_from.to_dict()
        # override the default output from pydantic by calling `to_dict()` of to
        if self.to:
            _dict['to'] = self.to.to_dict()
        # set to None if preset (nullable) is None
        # and __fields_set__ contains the field
        if self.preset is None and "preset" in self.__fields_set__:
            _dict['preset'] = None

        # set to None if time_zone (nullable) is None
        # and __fields_set__ contains the field
        if self.time_zone is None and "time_zone" in self.__fields_set__:
            _dict['timeZone'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TimeRange:
        """Create an instance of TimeRange from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TimeRange.parse_obj(obj)

        _obj = TimeRange.parse_obj({
            "preset": obj.get("preset"),
            "var_from": RelativeBoundary.from_dict(obj.get("from")) if obj.get("from") is not None else None,
            "to": RelativeBoundary.from_dict(obj.get("to")) if obj.get("to") is not None else None,
            "time_zone": obj.get("timeZone")
        })
        return _obj

TimeRange.update_forward_refs()
